# Example config for ziggiz-courier-pickup-syslog
[listen]
protocol = "udp"  # udp, tcp, or unix
host = "0.0.0.0"
port = 514
unix_socket = ""

[framing]
detect = true
mode = ""  # "octet" or "delimiter", empty for auto-detect
eom = "\n"

[kafka]
bootstrap_servers = "localhost:9092"
topic = "syslog"
compression_type = "gzip"
batch_size = 16384
