# Ziggiz Courier Pickup Syslog Server Configuration

# Server configuration
host: "::"
protocol: "udp"  # tcp or udp
port: 1514  # Using a non-privileged port for testing

# Logging configuration
log_level: "DEBUG"
log_format: "%(asctime)s %(levelname)s %(name)s %(message)s"
log_date_format: "%Y-%m-%d %H:%M:%S"

# Optional logger configurations
loggers:
  - name: "ziggiz_courier_pickup_syslog"
    level: "DEBUG"
    propagate: true
  - name: "asyncio"
    level: "WARNING"
    propagate: true
