# Ziggiz Courier Pickup Syslog Server Configuration

# Server configuration
host: "::"
protocol: "udp"  # tcp, udp, or unix
port: 1514  # Using a non-privileged port for testing
unix_socket_path: "/tmp/ziggiz-syslog.sock"  # Path for Unix socket when protocol is "unix"

# Framing configuration
framing_mode: "auto"  # auto, transparent, or non_transparent
end_of_message_marker: "\\n"  # End of message marker for non-transparent framing
max_message_length: 16384  # Maximum message length in bytes for non-transparent framing

# Logging configuration
log_level: "DEBUG"
log_format: "%(asctime)s %(levelname)s %(name)s %(message)s"
log_date_format: "%Y-%m-%d %H:%M:%S"

# Optional logger configurations
loggers:
  - name: "ziggiz_courier_pickup_syslog"
    level: "DEBUG"
    propagate: true
  - name: "asyncio"
    level: "WARNING"
    propagate: true
