# Ziggiz Courier Pickup Syslog Server Configuration with Unix Protocol

# Server configuration
protocol: "unix"  # Using unix protocol
unix_socket_path: "/var/run/ziggiz-syslog.sock"  # Path for Unix socket

# Framing configuration
framing_mode: "transparent"  # auto, transparent, or non_transparent
end_of_message_marker: "\\n"  # End of message marker for non-transparent framing
max_message_length: 16384  # Maximum message length in bytes for non-transparent framing

# Decoder configuration
decoder_type: "rfc5424"  # Syslog decoder type: "auto", "rfc3164", "rfc5424", or "base"

# Logging configuration
log_level: "INFO"
log_format: "%(asctime)s %(levelname)s %(name)s %(message)s"
log_date_format: "%Y-%m-%d %H:%M:%S"

# Optional logger configurations
loggers:
  - name: "ziggiz_courier_pickup_syslog"
    level: "INFO"
    propagate: true
  - name: "asyncio"
    level: "WARNING"
    propagate: true
