# Ziggiz Courier Pickup Syslog Server Configuration with Unix Protocol

# Server configuration
protocol: "unix"  # Using unix protocol
unix_socket_path: "/var/run/ziggiz-syslog.sock"  # Path for Unix socket

# Logging configuration
log_level: "INFO"
log_format: "%(asctime)s %(levelname)s %(name)s %(message)s"
log_date_format: "%Y-%m-%d %H:%M:%S"

# Optional logger configurations
loggers:
  - name: "ziggiz_courier_pickup_syslog"
    level: "INFO"
    propagate: true
  - name: "asyncio"
    level: "WARNING"
    propagate: true
