apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: strimzi-operator
spec:
  releaseName: strimzi-operator
  chart:
    spec:
      chart: strimzi-kafka-operator
      version: 0.46.0
      sourceRef:
        kind: HelmRepository
        name: strimzi-charts
        namespace: flux-system
  interval: 5m
  values:
    # Add any custom values here
    watchAnyNamespace: true
