# Ziggiz Courier Pickup Syslog Server Configuration - Basic Example
# This is a basic configuration for a TCP syslog server

# Server configuration
host: "::"           # IPv6 address to bind to (for dual stack support)
protocol: "tcp"      # Protocol to use: "tcp", "udp", "unix", or "tls"
port: 514            # Port to listen on
# unix_socket_path: "/var/run/ziggiz-syslog.sock"  # Path for Unix socket when protocol is "unix"

# IP filtering configuration
allowed_ips: []      # List of allowed IP addresses/networks (empty list means allow all)
                     # Examples: ["192.168.1.0/24", "10.0.0.5", "2001:db8::/64"]
deny_action: "drop"  # Action to take for denied connections: "drop" or "reject"

# Framing configuration
framing_mode: "auto" # Message framing mode: "auto", "transparent", or "non_transparent"
end_of_message_marker: "\\n"  # End of message marker for non-transparent framing
max_message_length: 16384  # Maximum message length in bytes for non-transparent framing

# Decoder configuration
decoder_type: "auto"  # Syslog decoder type: "auto", "rfc3164", "rfc5424", or "base"

# Output backend configuration
output_backend: "console"  # "console" or "kafka"
kafka_bootstrap_servers: "localhost:9092"
kafka_topic: "syslog-messages"

# Logging configuration
log_level: "INFO"    # Root logger level: DEBUG, INFO, WARNING, ERROR, CRITICAL
log_format: "%(asctime)s %(levelname)s %(name)s %(message)s"
log_date_format: "%Y-%m-%d %H:%M:%S"

# Individual logger configurations
loggers:
  - name: "ziggiz_courier_pickup_syslog"
    level: "INFO"
    propagate: true

  - name: "ziggiz_courier_pickup_syslog.protocol"
    level: "INFO"
    propagate: true

  - name: "ziggiz_courier_pickup_syslog.protocol.tcp"
    level: "INFO"
    propagate: true

  - name: "ziggiz_courier_pickup_syslog.protocol.udp"
    level: "INFO"
    propagate: true

  # Third-party libraries
  - name: "aiokafka"
    level: "WARNING"
    propagate: true

# Additional configuration options can be added here
