# Ziggiz Courier Pickup Syslog Server Configuration - Unix Socket Example
# This configuration sets up a syslog server using a Unix socket

# Server configuration
protocol: "unix"     # Use Unix socket protocol
unix_socket_path: "/var/run/ziggiz-syslog.sock"  # Path for Unix socket

# Framing configuration
framing_mode: "non_transparent"  # Use non-transparent framing
end_of_message_marker: "\n"      # End of message marker for non-transparent framing
max_message_length: 16384        # Maximum message length in bytes

# Decoder configuration
decoder_type: "rfc5424"  # Use RFC 5424 decoder (structured syslog format)

# Logging configuration
log_level: "INFO"    # Root logger level: DEBUG, INFO, WARNING, ERROR, CRITICAL
log_format: "%(asctime)s %(levelname)s %(name)s %(message)s"
log_date_format: "%Y-%m-%d %H:%M:%S"

# Individual logger configurations
loggers:
  - name: "ziggiz_courier_pickup_syslog"
    level: "INFO"
    propagate: true
