# Ziggiz Courier Pickup Syslog Server Configuration - UDP Example
# This configuration sets up a UDP syslog server

# Server configuration
host: "0.0.0.0"      # IPv4 address to bind to
protocol: "udp"      # Use UDP protocol
port: 514            # Standard syslog port

# Framing configuration
framing_mode: "auto" # Message framing mode: "auto", "transparent", or "non_transparent"
max_message_length: 8192  # Maximum message length in bytes (smaller for UDP to avoid fragmentation)

# Decoder configuration
decoder_type: "rfc3164"  # Use RFC 3164 decoder (traditional BSD syslog format)

# Logging configuration
log_level: "INFO"    # Root logger level: DEBUG, INFO, WARNING, ERROR, CRITICAL
log_format: "%(asctime)s %(levelname)s %(name)s %(message)s"
log_date_format: "%Y-%m-%d %H:%M:%S"

# Individual logger configurations
loggers:
  - name: "ziggiz_courier_pickup_syslog"
    level: "INFO"
    propagate: true

  - name: "ziggiz_courier_pickup_syslog.protocol.udp"
    level: "DEBUG"  # Set UDP protocol logger to DEBUG level for more detailed information
    propagate: true
